### ISSUE TITLE
Video-Größen

### ISSUE THREAD

**Issue by lagerlit** [RRZE-Webteam/fau-video#3]
Hallo, 

ich habe zum ersten Mal ein Vimeo-Video eingebunden - es läuft zu breit. (siehe screenshot)
![vimeo-video](https://cloud.githubusercontent.com/assets/9449835/6916477/e2aeda0c-d79c-11e4-95cc-6a2232ca20f3.JPG)

auf fau.eu habe ich auch zum ersten Mal ein Video eingebunden (youtube) - es läuft zu schmal. (siehe screenshot)
![screenshot-video-eu](https://cloud.githubusercontent.com/assets/9449835/6916500/11866fde-d79d-11e4-9d06-2d845e4ac20b.JPG)
Ausprobiert: auch Vimeo-Videos laufen so schmal. 

Kann mir da jemand schnell was fixen? Würde gern noch vor Ostern was mit Video auf fau.de posten. 

Viele Grüße
Luisa

**Comment by lagerlit** [comment]
Beitrag 1 ist wieder auf Entwurfstatus (Könnt ihr die Vorschau eingeloggt sehen? https://www.fau.de/?p=1114604&preview=true
Beitrag 2 ist veröffentlicht: https://www.fau.de/?p=1114604&preview=true

@xwolfde

**Comment by xwolfde** [comment]
Öh... und was hat das FAU-Video-Plugin mit YouTube und Vimeo zu tun?
Dies Plugin beschäftigt sich nur mit der Einbindung von Videos aus dem Videoportal.
Mit der Einbindung von Vimeo und YouTube hat das Plugin nichts zu tun. 

Die Darstellung von Vimeo und YouTube ist Theme-Sache (= Optik), wäre also dort ggf. als Issue einzutragen. 
Schnell fixen ist da aber leider nicht.
